#libonnxruntime = "/usr/lib64/libonnxruntime.so"

[eye]
#link = true
model = "eyeModel.onnx" # If not specified, tracking will be disabled.

[eye.left]
camera = "Bigeye: Bigeye (800x400 @ 90fps)" # If not specified, tracking will be disabled.

#[eye.left.crop]
#scale = 1.0
#major_shift = 0.0
#minor_shift = 0.0

#[eye.left.transform]
#rotation = 0.0
#brightness = 0.66
#vertical_flip = false
#horizontal_flip = false

[eye.right]
camera = "Bigeye: Bigeye (800x400 @ 90fps)" # If not specified, tracking will be disabled.

#[eye.right.crop]
#scale = 1.0
#major_shift = 0.0
#minor_shift = 0.0

#[eye.right.transform]
#rotation = 0.0
#brightness = 0.66
#vertical_flip = false
#horizontal_flip = false

[face]
# You can use a URL like "http://127.0.0.1:8080/mjpeg/stream.jpg" here as well.
camera = "USB 2.0 Camera: USB Camera (640x480 @ 30fps)" # If not specified, tracking will be disabled.
model = "faceModel.onnx" # If not specified, tracking will be disabled.

#[face.crop]
#scale = 1.0
#major_shift = 0.0
#minor_shift = 0.0

#[face.transform]
#rotation = 0.0
#brightness = 0.66
#vertical_flip = false
#horizontal_flip = false

[train]
baseline = "eyeModel.safetensors"

#[output.osc]
#destination = "127.0.0.1:9400"
